title: The Tiger's personal website
description: 心随朗月高，志与秋霜洁。
theme: jekyll-theme-cayman

gitment:
  enable: true
  github_user: MrHrh
  github_repo: github.io #新建一个存储评论的仓库，这里填写仓库名
  client_id: faa6d41c90b7064a1279 #第一步注册的client_id
  client_secret: 0fde80174f101981a0041d1376cb71c966703382 #第一步注册的client_secret
